### ISSUE TITLE
[Request] Extend datetime to allow for multiple outputs / timezones

### ISSUE THREAD

**Issue by kitallen23** [GustavoKatel/sidebar.nvim#1]
Hi there - fantastic job on this plugin, thank you! I can't wait to play around with it more when I have some time.

I was thinking about the usefulness of the datetime section, and how it would be fantastic if I could see the current time in other countries, as I have coworkers all over. Is this something that you would consider?

**Comment by GustavoKatel** [comment]
hi! thank you for the interest. I think this is a fantastic idea! it is something I find useful to me as well. I'll put to the roadmap.

**Comment by GustavoKatel** [comment]
hi @kitallen23 are you willing to test the `dev` branch? 

There are instructions [here](https://github.com/GustavoKatel/sidebar.nvim/tree/dev#datetime) on how to configure and extra dependencies (optional)

![image](https://user-images.githubusercontent.com/1891977/134744238-33cf6ace-e228-4436-8fb1-abc5a018576f.png)
