### ISSUE TITLE
Better error message for when a invalid section name is specified

### ISSUE THREAD

**Issue by IndianBoy42** [GustavoKatel/sidebar.nvim#2]
Just now while trying to setup sidebar.nvim, i was getting a confusing error message about trying to index a nil value in `bindings.lua`. The only way I figured out that it was because i used `diagnostics` not `lsp-diagnostics`, was by reading the code and guessing.

I think inside `resolve_section` or `get_builtin_section` a better error message could be printed to show that a builtin section was not found, or a invalid custom section was passed in (no `draw()` function or something)

**Comment by GustavoKatel** [comment]
good catch! I will update the docs and improve the error messages

**Comment by GustavoKatel** [comment]
should be resolved in the `dev` branch. Feel free to test. Will leave this open until I merge to main.

Feel free to test :D
