### ISSUE TITLE
Cannot disable docker section

### ISSUE THREAD

**Issue by karlc1** [GustavoKatel/sidebar.nvim#3]
I really have two issues with this plugin. The first is that when I start nvim with this plugin, it spawns an instance of dockerd that immediately uses up 100% cpu resources and slows down the entire computer. The second is that it does this even if I explicitly omit the "containers" section from the config. It also shows the UI for containers in the sidebar regardless of config.

**Comment by GustavoKatel** [comment]
interesting! can you post your sidebar configuration please?

**Comment by karlc1** [comment]
Sure, I just used the one from the readme: 

```
require("sidebar-nvim").setup({
    disable_default_keybindings = 0,
    bindings = nil,
    open = false,
    side = "left",
    initial_width = 35,
    update_interval = 1000,
    sections = { "datetime", "git-status", "diagnostics" },
    section_separator = "-----"
})
```
I assume that the docker stuff would not load since it's not defined in the `sections` field.

**Comment by GustavoKatel** [comment]
you are correct. it's not supposed to load. I will take a look later today. thanks for sharing

**Comment by GustavoKatel** [comment]
hi @karlc1 just merged a fix, are you willing to try that and see if it resolves your issue?

**Comment by cseickel** [comment]
hi @GustavoKatel, I just tried this plugin and I have the same problem.
`use {
    'GustavoKatel/sidebar.nvim',
    rocks = {'luatz'},
    config = function ()
        require('sidebar-nvim').setup({
            datetime = {
                format = "%a %b %d, %H:%M",
                clocks = {
                    { tz = "UTC" },
                    { tz = "America/New_York" }
                }
            },
            docker = {
                show_all = false
            },
            initial_width = 40,
            sections = { "datetime", "git-status", "lsp-diagnostics" }
        })
    end
} `

I had the same problem without the docker section, I just added that hoping it would fix the 100% cpu problem. It didn't.

**Comment by GustavoKatel** [comment]
hi @cseickel thanks for testing! I pushed again to `dev`. Can you update and try again?

Make sure to point packer to `branch = 'dev'`

**Comment by cseickel** [comment]
The dev branch does allow me to remove the docker section. It does, however break docker because now if I try to add it back in the sections I get this error:
```
[SidebarNvim] error trying to load section: docker
```

That's ok for me because I don't think I need docker in the sidebar.

**Comment by GustavoKatel** [comment]
the section name is `containers` and not `docker`. It failed bc it tried to load a section that does not exist.

**Comment by cseickel** [comment]
Well, that would explain it. It does work when I use `containers`. It also still kills my CPU. I ran `docker ps -a --format='{{json .}}'` in a terminal just to see what happened and it took 46 seconds to return and used a lot of CPU. I can see how calling that every second would kill a computer.

I don't know why, but the json format seems to be what makes it take so long. Without that it returns instantly.

**Comment by GustavoKatel** [comment]
>  I can see how calling that every second would kill a computer.

yeah, that's not good, I will not enable this section by default with a note on the README. Thanks again for testing.

**Comment by GustavoKatel** [comment]
@cseickel just thought about this. Would you mind testing this command:

`docker ps -a --format='{"Names": "{{.Names}}", "State": "{{.State }}", "ID": "{{.ID }}" }'`

Is it slow/faster/the same?

**Comment by cseickel** [comment]
Yes! Both of them run instantly and have the same output.

**Comment by GustavoKatel** [comment]
awesome thanks! sounds like a good improvement. will work on this later this week

**Comment by karlc1** [comment]
I just tried the dev branch and it does let me disable the docker integration. That is enough for me at least since I rarely use docker in development. However, 'I do get the error `error trying to load section: diagnostics` now, I'm not sure if that is new for the dev branch or if it happened on master as well, since my computer froze using the master branch.

**Comment by GustavoKatel** [comment]
hi @karlc1 the section name is `lsp-diagnostics` and not `diagnostics`

**Comment by GustavoKatel** [comment]
@karlc1 @cseickel just pushed some docker improvements to the `dev` branch, if you ever have the time to test it out I would appreciate the feedback. Thanks!

**Comment by cseickel** [comment]
@GustavoKatel I'm sorry to say that I uninstalled this plugin after having trouble with git commands. It seems like running even running git status is enough to lock a file and cause an error when running other git commands at the same time.

The core issue here that needs to be addressed before this plugin is is ready for prime time is to stop polling and start updating on events. Each section should have a specific set of events it listens to and maybe a function that further filters whether or not it needs to run the update based on the details of that event, such as what file was updated.

Those events then need to be debounced and ensure that there are not more than x updates run per y seconds.

Also, it should stop updating entirely if the sidebar is not currently visible. It can still keep track of what components are dirty, but it should not call any external programs or do any meaningful work while not visible.

**Comment by GustavoKatel** [comment]
@cseickel thank you for the super valuable feedback! I have a similar thing going on in the todos section and I guess this will make a very solid improvement to the other sections as well. sad to see you go tho, I will make sure to address the comments.
