### ISSUE TITLE
Run draw at least once when sidebar is opened

### ISSUE THREAD

**Issue by dsych** [GustavoKatel/sidebar.nvim#5]
## Context
Consider that case when `update_interval` is set to a relatively large value, say 10s. In this case we will need to wait for 10s before anything is rendered on the sidebar.
## Proposed solution
Run `draw` for each section at least once when sidebar becomes visible.

**Comment by GustavoKatel** [comment]
Hi @dsych I've done some improvements in the `dev` branch and I hope this will be resolved. Are you willing to test that?

TIA!

**Comment by dsych** [comment]
Sorry for late reply. I tested the dev branch and the problem still persists. Here is a minimal viable config:
```vim
" i am using vimplug
Plug 'GustavoKatel/sidebar.nvim', { 'branch': 'dev' }

lua << EOF
require("sidebar-nvim").setup({
  update_interval = 20000,
  sections = { "datetime" },
})
EOF

```
## Expected:
`:SidebarNvimToggle` should open a sidebar that display a `datetime` section.
## Actual:
`:SidebarNvimToggle` opens a split and waits for `update_interval`, in this case *20 seconds*, before displaying the sections.

**Comment by GustavoKatel** [comment]
aah thanks a lot for testing! I think I found the issue. The view was not being updated when it started closed. Can you update and try again?

Let me know if that resolves it for you.
